language: node_js

node_js:
    - "8.10.0"

install:
    - npm install
    - cd pdf-generator && npm install ; cd -

script:
  - npm run build && npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  local_dir: public
  repo: xotonic/xotonic.github.com
  on:
      branch: master 

